services:
  - type: web
    name: e-commerce-backend
    env: docker
    region: oregon
    plan: free
    branch: master
    rootDir: e-commerce
    envVars:
      - key: PORT
        value: 5454
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ecommerce-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ecommerce-db
          property: databaseName

databases:
  - name: ecommerce-db
    databaseName: ecommerce_db
    user: ecommerce
    plan: free
    region: oregon
